### ISSUE TITLE
Why `features/support` rather than `features/step_definitions`?

### ISSUE THREAD

**Issue by pauldesmondparker** [formentor-studio/dapp-auction-with-bdd-cucumber#2]
This was changed in the last merge and there is no reference to why in the commit log.

I noticed that the [cucumber-js README](https://github.com/cucumber/cucumber-js) has an example that uses the `support` sub-directory, but it's not necessary. This directory seems to be able to be called anything at all, or the tests can even be dumped in with the features with no ill-effect, other than OCD mental trauma.
![image](https://github.com/formentor-studio/dapp-auction-with-bdd-cucumber/assets/114397409/b23590a1-6534-497a-abc4-8f379be47062)

**Comment by joaquin-alfaro** [comment]
You are completely right. In recent projects we are using `step-definitions` and coding the tests with typescript.
